# Environment Args
output_root: '../'
pytorch_data_dir: 'pytorch-data'
submitting_to_aml: false

# Dataset args
dataset: "cocostuff"

# Model Args
model_type: "vit"
activation_type: "token"

# Upsampling args
outlier_detection: True
upsampler_type: "jbu_stack" # jbu_stack | transformer | unet_guided | bilinear
downsampler_type: "attention"
max_pad: 20
max_zoom: 2
n_jitters: 5
random_projection: 30
crf_weight: 0.001
filter_ent_weight: 0.0
tv_weight: 0.0
loss: "multiview_loss" # multiview_loss | simple_loss

implicit_sup_weight: 1.0

# Training args
batch_size: 2
epochs: 1
num_gpus: 1
num_workers: 12
lr: 1e-3

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~
